name: Sync with Upstream

on:
  schedule:
    - cron: '0 4 * * *'  # 2025.1.15: 北京时间12点自动运行
  workflow_dispatch:

permissions:
  contents: write  # 2026.1.15: 允许写入

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Configure Git
      run: |
        # git config user.name 'Shanwer'
        # git config user.email 'Shanwer@qq.com'
        
        # 2026.1.15: 提交用户改为 github-actions[bot]
        git config user.name 'github-actions[bot]'
        git config user.email 'github-actions[bot]@users.noreply.github.com'

    - name: Add upstream remote
      run: git remote add upstream https://github.com/GeyserMC/Geyser.git

    - name: Fetch upstream changes
      run: git fetch upstream

    - name: Merge upstream changes
      run: |
        git merge upstream/master || {
          echo "Merge conflict detected! Notifying for manual intervention."
          exit 1
        }
      
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: 'master'
